# Generated by Django 2.1.5 on 2020-05-10 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200510_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 19, 16, 21, 689284), verbose_name='date published'),
        ),
    ]
